name: 'Uffizzi Preview'
description: 'Deploy Continuous Previews on Uffizzi'
author: 'Adam Vollrath'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  compose-file:
    description: 'An alternate compose file'
    required: false
    default: 'docker-compose.yaml'
  hostname:
    description: 'URL to Uffizzi'
    required: false
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: true
  password:
    description: 'Uffizzi password'
    required: true
  project:
    description: 'Uffizzi project name'
    required: true
runs:
  using: 'docker'
  image: 'docker://uffizzi/cli:qa'
  args:
    - 'preview'
    - 'create'
    - ${{ inputs.compose-file }}
  env:
    UFFIZZI_PASSWORD: ${{ inputs.password }}
    UFFIZZI_HOSTNAME: ${{ inputs.hostname }}
    UFFIZZI_USER: ${{ inputs.username }}
    UFFIZZI_PROJECT: ${{ inputs.project }}
